# Use public servers from the pool.ntp.org project.
pool pool.ntp.org iburst

# Record the rate at which the system clock gains/losses time.
driftfile /var/lib/chrony/chrony.drift

# Allow the system clock to be stepped in the first three updates
# if its offset is larger than 1 second.
makestep 1.0 3

# Synchronize system clock
rtcsync

# Log to ISO8601 with milliseconds format config in syslog (via ansible or manual rsyslog tweaks)
log tracking measurements statistics
logdir /var/log/chrony
log change 0.1
