version: '3.8'
services:
  tritonserver:
    image: nvcr.io/nvidia/tritonserver:23.12-py3
    container_name: triton
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8002:8002"
    command: tritonserver --model-repository=/models --log-verbose=1
    volumes:
      - ./models:/models
    deploy:
      resources:
        limits:
          cpus: '8.0'
          memory: 16G
